export const getGreetingByLanguage = (languageCode: string): string => {
  const greetings: { [key: string]: string } = {
    'en': 'Good morning',
    'es': 'Buenos días',
    'fr': 'Bonjour',
    'de': 'Guten Morgen',
    'it': 'Buongiorno',
    'pt': 'Bom dia',
    'ru': 'Доброе утро',
    'ja': 'おはようございます',
    'ko': '좋은 아침입니다',
    'zh': '早上好',
    'zh-TW': '早上好',
    'ar': 'صباح الخير',
    'hi': 'सुप्रभात',
    'bn': 'সুপ্রভাত',
    'pa': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    'ta': 'காலை வணக்கம்',
    'te': 'శుభోదయం',
    'mr': 'शुभ सकाळ',
    'gu': 'સુપ્રભાત',
    'kn': 'ಶುಭೋದಯ',
    'ml': 'സുപ്രഭാതം',
    'th': 'สวัสดีตอนเช้า',
    'vi': 'Chào buổi sáng',
    'id': 'Selamat pagi',
    'ms': 'Selamat pagi',
    'tr': 'Günaydın',
    'pl': 'Dzień dobry',
    'nl': 'Goedemorgen',
    'sv': 'God morgon',
    'da': 'Godmorgen',
    'no': 'God morgen',
    'fi': 'Hyvää huomenta',
    'he': 'בוקר טוב',
    'cs': 'Dobré ráno',
    'sk': 'Dobré ráno',
    'hu': 'Jó reggelt',
    'ro': 'Bună dimineața',
    'bg': 'Добро утро',
    'hr': 'Dobro jutro',
    'sr': 'Добро јутро',
    'sl': 'Dobro jutro',
    'et': 'Tere hommikust',
    'lv': 'Labrīt',
    'lt': 'Labas rytas',
    'uk': 'Доброго ранку',
    'el': 'Καλημέρα',
    'mk': 'Добро утро',
    'sq': 'Miremengjes',
    'mt': 'Bongu',
    'is': 'Góðan daginn',
    'ga': 'Maidin mhaith',
    'cy': 'Bore da',
    'eu': 'Egun on',
    'ca': 'Bon dia',
    'gl': 'Bos días',
    'be': 'Добрай раніцы',
    'uz': 'Xayrli tong',
    'kk': 'Қайырлы таң',
    'ky': 'Кутман таң',
    'tg': 'Субҳ баҳор',
    'tk': 'Ertiriňiz ýagşy bolsun',
    'az': 'Sabahınız xeyir',
    'hy': 'Բարև լինի',
    'ka': 'დილამარჯვა',
    'am': 'እንደምን ይሁኑ',
    'sw': 'Habari za asubuhi',
    'zu': 'Sawubona',
    'af': 'Goeie more',
    'xh': 'Molo',
    'st': 'Mohlare',
    'tn': 'Mokibelo',
    'sn': 'Mangwanani',
    'yo': 'E kaaro',
    'ig': 'Ụtụtụ ọma',
    'ha': 'Sannu da safe',
    'ne': 'शुभ प्रभात',
    'si': 'සුභපහේවින්',
    'my': 'မင်္ဂလာနေကြာ',
    'km': 'អរុណសួស្តី',
    'lo': 'ສະບາຍດູ່ຕອນເຊົ້າ',
    'mn': 'Өглөө морь',
    'dz': 'སང་པ་མགུར་བསྔགས།',
    'bo': 'སྐུ་འགྲོལ་ལེགས་སོ།',
    'fa': 'صبح بخیر',
    'ps': 'سهار مو پخیر دی',
    'sd': 'سڀاڀي صبح',
    'ur': 'صبح بخیر',
  };

  return greetings[languageCode] || greetings['en'];
};

export const getTimeBasedGreetingByLanguage = (languageCode: string): string => {
  const hour = new Date().getHours();
  
  if (hour < 12) {
    return getGreetingByLanguage(languageCode);
  } else if (hour < 17) {
    const afternoonGreetings: { [key: string]: string } = {
      'en': 'Good afternoon',
      'es': 'Buenas tardes',
      'fr': 'Bon après-midi',
      'de': 'Guten Tag',
      'it': 'Buon pomeriggio',
      'pt': 'Boa tarde',
      'ru': 'Добрый день',
      'ja': 'こんにちは',
      'ko': '안녕하세요',
      'zh': '下午好',
      'zh-TW': '下午好',
      'ar': 'طاب مساؤك',
      'hi': 'शुभ दोपहर',
      'bn': 'শুভ বিকেল',
      'pa': 'ਸ਼ਾਮ ਚੰਗੀ',
      'ta': 'மதிய வணக்கம்',
      'te': 'శుభ మధ్యాహ్నం',
      'mr': 'शुभ दुपार',
      'gu': 'શુભ બપોર',
      'kn': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      'ml': 'ശുഭ ഉച്ച',
      'th': 'สวัสดีตอนบ่าย',
      'vi': 'Chào buổi chiều',
      'id': 'Selamat siang',
      'ms': 'Selamat tengah hari',
      'tr': 'İyi günler',
      'pl': 'Dzień dobry',
      'nl': 'Goedemiddag',
      'sv': 'God eftermiddag',
      'da': 'God eftermiddag',
      'no': 'God ettermiddag',
      'fi': 'Hyvää päivää',
      'he': 'צוהר טוב',
      'cs': 'Dobré odpoledne',
      'sk': 'Dobré popoludnie',
      'hu': 'Jó napot',
      'ro': 'Bună ziua',
      'bg': 'Добър ден',
      'hr': 'Dobar dan',
      'sr': 'Добар дан',
      'sl': 'Dober dan',
      'et': 'Tere päevast',
      'lv': 'Labdien',
      'lt': 'Labą dieną',
      'uk': 'Доброго дня',
      'el': 'Καλημέρα',
      'mk': 'Добар ден',
      'sq': 'Mirembrema',
      'mt': 'Wara nofsinhar',
      'is': 'Góðan daginn',
      'ga': 'Tráthnóna maith',
      'cy': 'Prynhawn da',
      'eu': 'Egun on',
      'ca': 'Bona tarda',
      'gl': 'Boa tarde',
      'be': 'Добры дзень',
      'uz': 'Xayrli tushlik',
      'kk': 'Қайырлы күн',
      'ky': 'Кутман күн',
      'tg': 'Рӯз баҳур',
      'tk': 'Günüňiz ýagşy bolsun',
      'az': 'Gününüz xeyir',
      'hy': 'Բարև ցեր',
      'ka': 'გამარჯობა',
      'am': 'እንደምን ይሁን',
      'sw': 'Habari za mchana',
      'zu': 'Sawubona',
      'af': 'Goeie middag',
      'xh': 'Molo',
      'st': 'Mohlare',
      'tn': 'Mokibelo',
      'sn': 'Masikati',
      'yo': 'E kaasan',
      'ig': 'Ehihie ọma',
      'ha': 'Sannu da yamma',
      'ne': 'शुभ दिउँसो',
      'si': 'සුභ සන්ධ්‍යාව',
      'my': 'မင်္ဂလာနေ့လည်း',
      'km': 'ជំនាប់ល្អ',
      'lo': 'ສະບາຍດູ່ຕອນເທດ',
      'mn': 'Өдрийн мэнд',
      'dz': 'ཉིན་གུང་མགུར་བསྔགས།',
      'bo': 'ཉིན་གུང་བདེ་ལེགས།',
      'fa': 'ظهر بخیر',
      'ps': 'ماسپخیر دی',
      'sd': 'سڀاڀي دوپھر',
      'ur': 'دوپہر بخیر',
    };
    return afternoonGreetings[languageCode] || afternoonGreetings['en'];
  } else {
    const eveningGreetings: { [key: string]: string } = {
      'en': 'Good evening',
      'es': 'Buenas noches',
      'fr': 'Bonsoir',
      'de': 'Guten Abend',
      'it': 'Buona sera',
      'pt': 'Boa noite',
      'ru': 'Добрый вечер',
      'ja': 'こんばんは',
      'ko': '안녕하세요',
      'zh': '晚上好',
      'zh-TW': '晚上好',
      'ar': 'مساء الخير',
      'hi': 'शुभ संध्या',
      'bn': 'শুভ সন্ধ্যা',
      'pa': 'ਸ਼ਾਮ ਚੰਗੀ',
      'ta': 'மாலை வணக்கம்',
      'te': 'శుభ సాయంత్రం',
      'mr': 'शुभ संध्याकाळ',
      'gu': 'શુભ સાંજ',
      'kn': 'ಶುಭ ಸಂಜೆ',
      'ml': 'ശുഭ സന്ധ്യ',
      'th': 'สวัสดีตอนเย็น',
      'vi': 'Chào buổi tối',
      'id': 'Selamat malam',
      'ms': 'Selamat malam',
      'tr': 'İyi akşamlar',
      'pl': 'Dobry wieczór',
      'nl': 'Goedenavond',
      'sv': 'God kväll',
      'da': 'Godaften',
      'no': 'God kveld',
      'fi': 'Hyvää iltaa',
      'he': 'ערב טוב',
      'cs': 'Dobrý večer',
      'sk': 'Dobrý večer',
      'hu': 'Jó estét',
      'ro': 'Bună seara',
      'bg': 'Добър вечер',
      'hr': 'Dobra večer',
      'sr': 'Добро вече',
      'sl': 'Dober večer',
      'et': 'Tere õhtust',
      'lv': 'Labvakar',
      'lt': 'Labas vakarą',
      'uk': 'Доброго вечора',
      'el': 'Καλησπέρα',
      'mk': 'Добар вечер',
      'sq': 'Mirembrëja',
      'mt': 'Filgħaxija',
      'is': 'Gott kvöld',
      'ga': 'Tráthnóna maith',
      'cy': 'Noswaith dda',
      'eu': 'Gau on',
      'ca': 'Bona nit',
      'gl': 'Boa noite',
      'be': 'Добры вечар',
      'uz': 'Xayrli kech',
      'kk': 'Қайырлы кеш',
      'ky': 'Кутман кеч',
      'tg': 'Шаб баҳур',
      'tk': 'Aýryňyz ýagşy bolsun',
      'az': 'Axşamınız xeyir',
      'hy': 'Բարև երեկո',
      'ka': 'დილამარჯვა',
      'am': 'እንደምን ይሁን',
      'sw': 'Habari za jioni',
      'zu': 'Sawubona',
      'af': 'Goeie naand',
      'xh': 'Molo',
      'st': 'Mohlare',
      'tn': 'Mokibelo',
      'sn': 'Manheru',
      'yo': 'E kaale',
      'ig': 'Ehihie ọma',
      'ha': 'Sannu da yamma',
      'ne': 'शुभ साँझ',
      'si': 'සුභ සන්ධ්‍යාව',
      'my': 'မင်္ဂလာညနေ',
      'km': 'ជំនាប់ល្អ',
      'lo': 'ສະບາຍດູ່ຕອນເຊົ້າ',
      'mn': 'Өдрийн мэнд',
      'dz': 'ཉིན་གུང་མགུར་བསྔགས།',
      'bo': 'ཉིན་གུང་བདེ་ལེགས།',
      'fa': 'شب بخیر',
      'ps': 'ماسپخیر دی',
      'sd': 'سڀاڀي سھ',
      'ur': 'شب بخیر',
    };
    return eveningGreetings[languageCode] || eveningGreetings['en'];
  }
};
